version: '3.7'

services:
  meilisearch:
    build:
      context: .
      dockerfile: ./docker/services/meilisearch/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_meilisearch
    container_name: ${DOCKER_PROJECT_NAME}_meilisearch
    networks:
      - net
    ports:
      - '${DOCKER_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - ./docker/scripts/meilisearch.sh:/scripts/meilisearch.sh
    environment:
      - PASSWORD=${DOCKER_MEILISEARCH_PASSWORD}
    command: /scripts/meilisearch.sh

  redis:
    build:
      context: .
      dockerfile: ./docker/services/redis/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_redis
    container_name: ${DOCKER_PROJECT_NAME}_redis
    networks:
      - net
    ports:
      - '${DOCKER_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker/scripts/redis.sh:/scripts/redis.sh
    environment:
      - PASSWORD=${DOCKER_REDIS_PASSWORD}
    command: /scripts/redis.sh
    depends_on:
      - meilisearch

  mysql:
    build:
      context: .
      dockerfile: ./docker/services/mysql/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_mysql
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    networks:
      - net
    ports:
      - '${DOCKER_MYSQL_PORT:-3306}:3306'
    volumes:
      - ./docker/services/mysql/conf/custom.cnf:/etc/mysql/custom.cnf
      - ./docker/services/mysql/var/backups/sql:/var/backups/sql
      # - ./docker/services/mysql/var/backups/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./docker/services/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
    depends_on:
      - meilisearch
      - redis

  php:
    build:
      context: .
      dockerfile: ./docker/services/php/${DOCKER_PHP_VERSION}/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_php
    container_name: ${DOCKER_PROJECT_NAME}_php
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
    - '9001:9001'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/supervisord.ini:/etc/supervisor.d/supervisord.ini
#      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/worker.ini:/etc/supervisor.d/worker.ini
      - ./docker/scripts/php.sh:/scripts/php.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - MYSQL_HOST=${DOCKER_PROJECT_NAME}_mysql
    command: /scripts/php.sh
    depends_on:
      - meilisearch
      - redis
      - mysql

  nodejs:
    build:
      context: .
      dockerfile: ./docker/services/nodejs/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_nodejs
    container_name: ${DOCKER_PROJECT_NAME}_nodejs
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
      - '${DOCKER_NODEJS_PORT:-3000}:3000'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/scripts/nodejs.sh:/scripts/nodejs.sh
    environment:
      - ROOT=${DOCKER_NODEJS_ROOT}
      - NPM_COMMAND=${DOCKER_NODEJS_NPM_COMMAND}
    command: /scripts/nodejs.sh
    depends_on:
      - meilisearch
      - redis
      - mysql
      - php

  golang:
    build:
      context: .
      dockerfile: ./docker/services/golang/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_golang
    container_name: ${DOCKER_PROJECT_NAME}_golang
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
      - '${DOCKER_GOLANG_PORT:-8000}:8000'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/scripts/golang.sh:/scripts/golang.sh
    environment:
      - ROOT=${DOCKER_GOLANG_ROOT}
      - GOLANG_COMMAND=${DOCKER_GOLANG_COMMAND}
    command: /scripts/golang.sh
    depends_on:
      - meilisearch
      - nodejs
      - redis
      - mysql
      - php

  nginx:
    build:
      context: .
      dockerfile: ./docker/services/nginx/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_nginx
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/services/nginx/conf.d/${DOCKER_NGINX_CONFIG}:/etc/nginx/conf.d/docker.conf.template
      - ./docker/scripts/nginx.sh:/scripts/nginx.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - SERVER_NAME=${DOCKER_PROJECT_DOMAIN}
      - ROOT=${DOCKER_NGINX_ROOT}
      - CONFIG=${DOCKER_NGINX_CONFIG}
      - PHP_HOST=${DOCKER_PROJECT_NAME}_php
      - NODEJS_HOST=${DOCKER_PROJECT_NAME}_nodejs
      - VIRTUAL_HOST=${DOCKER_PROJECT_DOMAIN}
    command: /scripts/nginx.sh
    depends_on:
      - meilisearch
      - golang
      - nodejs
      - redis
      - mysql
      - php

  phpmyadmin:
    build:
      context: .
      dockerfile: ./docker/services/phpmyadmin/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_phpmyadmin
    container_name: ${DOCKER_PROJECT_NAME}_phpmyadmin
    networks:
      - net
    volumes:
        - ./docker/services/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - '${DOCKER_PHPMYADMIN_PORT:-8008}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=${DOCKER_PHPMYADMIN_PMA_ABSOLUTE_URI}
      - PMA_HOST=${DOCKER_PROJECT_NAME}_mysql
      - PMA_PORT=3306
    depends_on:
      - meilisearch
      - golang
      - nodejs
      - redis
      - mysql
      - nginx
      - php

  cloud9:
    build:
      context: .
      dockerfile: ./docker/services/cloud9/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_cloud9
    container_name: ${DOCKER_PROJECT_NAME}_cloud9
    networks:
      - net
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
    ports:
      - '${DOCKER_CLOUD9_PORT:-8989}:8080'
    environment:
      - C9_WORKSPACE=${DOCKER_PROJECT_PATCH}
      - C9_EXTRA=${DOCKER_CLOUD9_C9_EXTRA}
    depends_on:
      - phpmyadmin
      - meilisearch
      - golang
      - nodejs
      - redis
      - mysql
      - nginx
      - php

networks:
  net:
    driver: bridge
